//独立COOKIE文件     ck在``里面填写，多账号换行

let qmydtokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgxNzY1NywiZXhwIjoyMDUzNjQxNzY1NywibmJmIjoxNjE0ODE3NjU3LCJqdGkiOiJNUEh5d2lkWE9wUHZnOUdFIiwic3ViIjoxMTU5OTcsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.JvVMSZM3NTKt1tBBK1N8DOQSpStGVeruoFlKQcI1CGo
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDg1NDY4MywiZXhwIjoyMDUzNjQ1NDY4MywibmJmIjoxNjE0ODU0NjgzLCJqdGkiOiJmb2Q1VmdoVk1iQzVIaEFCIiwic3ViIjoxMTY1MjYsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.9WdA1h6CSZFBqJJxjyl1gKattZMpjSoFgbDB-9ViFeg
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDg2NzYzNSwiZXhwIjoyMDUzNjQ2NzYzNSwibmJmIjoxNjE0ODY3NjM1LCJqdGkiOiI0SmxxWTRybVJoOXZZSTMxIiwic3ViIjoxMTY2NTcsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.L1sHIm5uTHNtM0CRDed4ow7CpnuPjwiw6LvEnhKa5YY`








let qmydcookie = {

    qmydtokenVal: qmydtokenVal,

}

module.exports = qmydcookie
