//独立COOKIE文件     ck在``里面填写，多账号换行

let yuedongzutokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0Njc1Mzg2LCJleHAiOjIwNTM2Mjc1Mzg2LCJuYmYiOjE2MTQ2NzUzODYsImp0aSI6InFTVVBwVzBlZzJxd3VzeVkiLCJzdWIiOjMxOTkwLCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.JdkicvHMtbm2ZiqspgQ5prKw0-627RSZ68n-MofccSY`



let yuedongzucookie = {
    yuedongzutokenVal: yuedongzutokenVal,

}

module.exports = yuedongzucookie
