//独立COOKIE文件     ck在``里面填写，多账号换行

let yuedongzutokenVal = `"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0NjgxODMwLCJleHAiOjIwNTM2MjgxODMwLCJuYmYiOjE2MTQ2ODE4MzAsImp0aSI6IkFKSFJOY0YyV0JBaGZOQmUiLCJzdWIiOjMxOTkwLCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.oyFBgfYFWvVanE_y7b1Mt-fzpWe2RlJLGwyjIiVf1O0
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0Njg2NTkxLCJleHAiOjIwNTM2Mjg2NTkxLCJuYmYiOjE2MTQ2ODY1OTEsImp0aSI6ImJIUlo1MjBROEtjQUs3NUUiLCJzdWIiOjMyMzg3LCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.tFaA0iPDy6PFtDJ0LP_wDek3_sbfCx8Ruor6bWzYTY0`



let yuedongzucookie = {
    yuedongzutokenVal: yuedongzutokenVal,

}

module.exports = yuedongzucookie
