//独立COOKIE文件     ck在``里面填写，多账号换行

let yuedongzutokenVal = `"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0NjgxODMwLCJleHAiOjIwNTM2MjgxODMwLCJuYmYiOjE2MTQ2ODE4MzAsImp0aSI6IkFKSFJOY0YyV0JBaGZOQmUiLCJzdWIiOjMxOTkwLCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.oyFBgfYFWvVanE_y7b1Mt-fzpWe2RlJLGwyjIiVf1O0
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0NjgxODMwLCJleHAiOjIwNTM2MjgxODMwLCJuYmYiOjE2MTQ2ODE4MzAsImp0aSI6IkFKSFJOY0YyV0JBaGZOQmUiLCJzdWIiOjMxOTkwLCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.oyFBgfYFWvVanE_y7b1Mt-fzpWe2RlJLGwyjIiVf1O0","yuedongzutoken2":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpbiIsImlhdCI6MTYxNDY4NjIwMiwiZXhwIjoyMDUzNjI4NjIwMiwibmJmIjoxNjE0Njg2MjAyLCJqdGkiOiJuUjhYNUpaWkZ5YzNMbk5pIiwic3ViIjozMjM4NywicHJ2IjoiNDFkZjg4MzRmMWI5OGY3MGVmYTYwYWFlZGVmNDIzNDEzNzAwNjkwYyJ9.YsScv8Xv4V3P3hsVNyqlJ3Iwaa5DI1PAP0-3FlawrL8`



let yuedongzucookie = {
    yuedongzutokenVal: yuedongzutokenVal,

}

module.exports = yuedongzucookie
