# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 闪挣

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  watch:
    types: sz
  repository_dispatch:
    types: start
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SZURL: ${{ secrets.SZURL }}
        SZHD: ${{ secrets.SZHD }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/willianmmiao/Action.git ~/Action
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/Action
          git checkout main
          npm install
      - name: '运行 【闪挣】'
        if: env.SZHD
        run: |
          cd ~/Action/Scripts
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣2】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣3】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣4】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣5】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣6】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣7】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣8】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣9】'   
        run: |
          node sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
