
name: 闪挣

on:
  workflow_dispatch:

  schedule:
     - cron: '12 */1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【闪挣1】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣2】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣3】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣4】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣5】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣6】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣7】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣8】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
      - name: '运行 【闪挣9】'   
        run: |
          node Scripts/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
